### PR TITLE
Make md5sum of generated kernel module consistent

### PR DESCRIPTION
**Pull request by kewu1992**
This PR makes the generated kernel module have consistent
md5sum accross different runs.

### CODE REVIEW

**Comment by rkolchmeyer** [comment]
Could you explain a bit how this solves the problem?

**Comment by kewu1992** [comment]
> Could you explain a bit how this solves the problem?

This fix was proposed by Nvidia people. Sorry I couldn't remember why it fixes the problem but I verified it works.

**Comment by rkolchmeyer** [comment]
> > Could you explain a bit how this solves the problem?
> 
> This fix was proposed by Nvidia people. Sorry I couldn't remember why it fixes the problem but I verified it works.

Could you put that in the code as a comment? Hopefully we can avoid accidentally reverting this fix through other changes.

**Comment by kewu1992** [comment]
> > > Could you explain a bit how this solves the problem?
> > 
> > 
> > This fix was proposed by Nvidia people. Sorry I couldn't remember why it fixes the problem but I verified it works.
> 
> Could you put that in the code as a comment? Hopefully we can avoid accidentally reverting this fix through other changes.

Done.

**Review by rkolchmeyer — APPROVED** [review]

**Pull request merged**
