### PR TITLE
Update default driver version to 390.46

### PR DESCRIPTION
**Pull request by rohitagarwal003**

### CODE REVIEW

**Comment by rohitagarwal003** [comment]
@kewu1992 Can you also push a new release to GCR after you merge this? Thanks!

**Comment by kewu1992** [comment]
Does k8s plan to use the installer with this new driver? Has the driver passed any qualification tests?

**Comment by rohitagarwal003** [comment]
It's passed the same tests which previous drivers passed.

We plan to switch the master branch (which is used in OSS PRs) to use this driver.

I also sent you an internal bug which this driver is supposed to fix.

**Comment by kewu1992** [comment]
OK. We can this first for cos-gpu-installer. But we may need more tests before we can bump the version on internal cos-gpu.

**Pull request merged**
