### PR TITLE
Update default driver version

### PR DESCRIPTION
**Pull request by stephensolis**
I'd like to use CUDA 9.1, which requires at least driver version 387.26 (https://github.com/NVIDIA/nvidia-docker/wiki/CUDA#requirements)

### CODE REVIEW

**Comment by stephensolis** [comment]
CLA signed (I hope)

**Comment by stephensolis** [comment]
CLA should be signed now

**Review by rohitagarwal003 — APPROVED** [review]

**Comment by sebbov** [comment]
Planning on merging this?  I could use the update here as well. Thanks!

**Comment by rohitagarwal003** [comment]
Someone still needs to push an updated docker image to GCR.

FWIW, people don't need to get blocked on the version getting updated in the `entrypoint.sh` script. `NVIDIA_DRIVER_VERSION`  can be overridden from an environment variable.

**Pull request merged**
